package com.ztemt.test.perf;

public class AppData {
    public static final String[][] DATA = {
        {
            "拨号",
            "com.android.contacts",
            ".DialerActivity"
        },
        {
            "联系人",
            "com.android.contacts",
            ".activities.PeopleActivity"
        },
        {
            "信息",
            "com.android.contacts",
            ".MmsConversationActivity"
        },
        {
            "相机",
            "com.android.camera",
            ".CameraLauncher"
        },
        {
            "浏览器",
            "com.android.browser",
            ".BrowserActivity"
        },
        {
            "设置",
            "com.android.settings",
            ".Settings"
        },
        {
            "搜索",
            "cn.nubia.quicksearchbox",
            ".SearchActivity"
        },
        {
            "手电筒",
            "cn.nubia.v5light.preset",
            "cn.nubia.v5light.MainActivity"
        },
        {
            "收音机",
            "cn.nubia.fmradio.preset",
            "cn.nubia.fmradio.FMRadio"
        },
        {
            "图库",
            "com.android.gallery3d",
            ".app.Gallery"
        },
        {
            "录音",
            "cn.nubia.soundrecorder.preset",
            "cn.nubia.soundrecorder.SoundRecorderBrowserActivity"
        },
        {
            "牛盾",
            "cn.nubia.security",
            ".NubiaSecurity"
        },
        {
            "记事本",
            "cn.nubia.notepad.preset",
            "cn.nubia.notepad.NoteListActivity"
        },
        {
            "时间管理",
            "cn.nubia.deskclock.preset",
            "cn.nubia.deskclock.DeskClock"
        },
        {
            "日程",
            "cn.nubia.calendar.preset",
            "cn.nubia.calendar.AllInOneActivity"
        },
        {
            "nubia视界",
            "cn.nubia.neoshare",
            ".login.AppStartActivity"
        },
        {
            "我的文件",
            "cn.nubia.myfile",
            ".CategoryActivity"
        },
        {
            "计算器",
            "cn.nubia.calculator2.preset",
            "cn.nubia.calculator2.Calculator"
        },
        {
            "主题",
            "cn.nubia.thememanager",
            ".activity.ThemeTabActivity"
        },
        {
            "蓝牙找寻器",
            "cn.nubia.bleobj",
            ".BleStartActivity"
        },
        {
            "互动分享",
            "cn.nubia.dlna",
            ".ui.StartActivity"
        },
        {
            "玩机手册",
            "cn.nubia.phonemanualintegrate.preset",
            ".MainActivity"
        },
        {
            "屏幕投影",
            "com.android.settings",
            ".wfd.WifiDisplaySettingsActivity"
        },
        {
            "蓝牙伴侣",
            "cn.nubia.btcompanion",
            "com.ztemt.btcompanion.BCStartActivity"
        },
        {
            "备份",
            "cn.nubia.databackup",
            ".ui.MainActivity"
        },
        {
            "视频",
            "com.android.video",
            ".list.app.VideoListActivity"
        },
        {
            "音乐",
            "cn.nubia.music.preset",
            "cn.nubia.music.MainActivity"
        },
        {
            "情景模式",
            "com.android.settings",
            ".Settings$ProfileSettingsActivity"
        },
        {
            "电子邮件",
            "com.android.email",
            ".activity.Welcome"
        },
        {
            "舒适度计",
            "cn.nubia.comfort",
            ".ui.ComfortActivity"
        }
    };
}
